#+TITLE: JustForFun读书感想
#+DATE: 2014-06-15
#+SETUPFILE: ~/CodeRepo/GitRepo/octopress/org-sty/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: life
#+JEKYLL_PUBLISHED: true
#+JEKYLL_COMMENTS: true

* JustForFun读书感想

** 来源
无意间发现了linus的自传，周末读了一下，感觉不错，记录一下感想。

** 摘录
#+BEGIN_QUOTE
有三件事具有生命的意义：第一是生存，第二是社会秩序，第三是娱乐。\\
一切事物都将从生存走向娱乐。\\
Just for Fun \\
#+END_QUOTE

#+BEGIN_QUOTE
我问他,如果见到比尔盖茨想说些什么,他却说连与后者见 一面的欲望都没有。\\
“在我们俩之间没有什么关系可言,”他说,“他所做的事是世界上最优秀的,但我却丝
毫不感兴趣。我所做的事在世界上也可能是最优秀的,他也不感兴趣。我对他经商
提不出任何建议,他对我的技术也提不出任何看法。”
#+END_QUOTE

#+BEGIN_QUOTE
强制性服兵役制度的主要原因就是让芬兰男人们在喝啤酒时有话可聊,而且他们能活多久
就能聊多久。生个人都忍受了许多痛苦,那是共同的。他们都恨军队,但事后聊起来时却又
都格外开心。
#+END_QUOTE

#+BEGIN_QUOTE
每个人都会一本改变其一生的书籍,比如《圣经》、《资本论》、《星期二和莫瑞在一起》、
《我想 知道我在幼儿园里学到的一切》等等. \\
把我推向生命高峰的是安德鲁?塔南鲍姆 (Andrew S. Tanenbaum)写的《操作系统:设计和实现》。
#+END_QUOTE

#+BEGIN_QUOTE
通过阅读和对 UNIX 的了解愈来愈深,我的热情高涨起来。\\
说实话,我的热情从来没有低落过(我希望你在做某件事时也能说出同样的话)。\\
#+END_QUOTE

#+BEGIN_QUOTE
UNIX的理念是越小越漂亮。一小堆简单基本的建筑材料,结合起来就能创造出无限的复杂表述。\\
#+END_QUOTE

#+BEGIN_QUOTE
编程给人带来的最初兴奋的原因有部分是显而易见的,\\
那就是:通过编程你可以支配一台计算机,你叫计算机做什么,它就做什么,永远准确无误,而且毫无怨言。
#+END_QUOTE

#+BEGIN_QUOTE
一个伟大的 编程者能凭借其聪明的头脑就知道答案是什么。他知道怎样写出漂亮的程序,知道怎样采用\\
一种全新的但最终会被证明是正确的方法。
#+END_QUOTE

#+BEGIN_QUOTE
在软件世界中,一旦你已解决了最根本的问题,兴趣就容易很快地消失
#+END_QUOTE

#+BEGIN_QUOTE
Linux 所取得的许多成功,其实可以归结为我的缺点所致: \\
1、 我很懒散。\\
2、 我喜欢授权给其他人。\\
#+END_QUOTE

#+BEGIN_QUOTE
我遇上了塔芙。她对我一生的影响甚至比《操作系统:设计与执行》一书对我的影响 还要大。\\
#+END_QUOTE

** 总结：
#+BEGIN_EXAMPLE
1. 做自己想做的事。
2. just for fun
#+END_EXAMPLE

{{{more}}}
