#+TITLE: 我的 2017
#+DATE: 2018-02-23
#+SETUPFILE: ~/CodeRepo/GitRepo/Road/blog/org/setupfile.org
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: life
#+JEKYLL_PUBLISHED: true
#+JEKYLL_COMMENTS: true

* 我的 2017

一转眼 2017 年就这样过了，年龄越大，对时间的流逝就越敏感，总想写点什么来记录我关于 2017 的思考，也顺便总结这几年工作的感想。

** 一切源自 30 岁之前必做的事
2016 年的某段时间，我习惯每天下班看 Quora，看到了这篇文章，[[https:////www.quora.com/What-are-10-things-that-you-should-definitely-do-before-turning-30][What are 10 things that you should definitely do before turning 30?]]
30岁之前必做的 10 件事，其中一个答案一条对我触动很深，*Live alone for at least a year*，至少独自在外居住一年，于是我便开始自己
租房子，开始一个人的生活。

{{{more}}}

** 独自生活一年
开始找房子的时候我经常想这个问题，为什么这个租房难这个问题还没有好的办法解决，我实在想不通哪里出了什么问题，但是肯定是哪里有问题，
一个人生活并没有想象中的生活不能自理，而自我对话和思考的时间多了，我挺喜欢一个人静静的思考问题，喜欢在安静的空间和自己对话。

** 做自己的产品
2017 我有很多 idea，想自己做自己的产品，自己使用，然后开始创业，事实证明，创业哪有那么简单，我虽然做了一些东西，但是总体来说都以
失败而告终。

*** whyushare 分享你的收藏
这个产品的原型是我觉得朋友圈都是一些没有营养的东西，而每个人收藏的东西才是真正有价值的，当我开始做的时候发现了 Pocket，国内的收趣等
一系列领先我几十年的东西，做出原型让同事试用后，我发现我没有一个让别人用我产品的理由，结果还乱七八糟做了一堆有的没的功能，最后做成
了一个浏览器插件，现在每天用的还挺好。

http:////cdn.defcoding.com/7939E1BA-D10A-4A6D-A646-A7EA75BA9A18.png

这个产品我学会了真正用快的方法先实现效果上线再说，而后续我打算做成一个 Chrome 插件，先上 Chrome 应用商店，至于社交功能以后真的有需求再说。

*** iDrag 上传图片到七牛云
这个产品相对比较成功，已经上到了 Mac App Store，由于开发者账号问题，我没法收费，就暂时免费、开源，这个工具我自己写文章的时候经常用，
我个人还是挺喜欢的，只是这种小东西并不能引起什么。

*** Oh My Creation
这个产品源自项目管理失控了，我想使用一种工具来管理产品的创造过程，开始定位是我自己每天必用的产品，事实证明我想太多，并没有达到我想象中
的效果，我还是偶尔会用这个产品，但是它给我的帮助并不大。

*** Twister
某天脑洞大开，不如用科大讯飞接口做一个绕口令游戏，原型是实现了，可惜没有动力继续下去，科大讯飞的语音识别还是很牛。

*** MentorHub
看了刻意练习这本书，我想做一个与众不同的教程网站，使用刻意练习的方法教新手学习，可惜具体到实行阶段就 GG，要落实的问题还有很多。

之所以想那么多一事无成，我觉得一是我不够专注，二是我不是天才，我需要一个 Team 才行。

** 读 N 本书
2017 对我来说最大的收获是我读书的时间多了，我读了很多书：

1. 刻意练习
2. 深度工作
3. 最重要的一件事，只有一件
4. 极客与团队
5. 证券分析
6. 安全边际
7. 投资最重要的事
8. 影响力
9. 谈判力
10. 魔鬼出没的世界
11. ... 至少 20 本，大多是投资

除了提升自己的眼界和独立思考的能力外，个人感觉看书的有种可意味的好处，读书的习惯要保持。

** 投资理财
读的书中有一本叫《穷查理宝典》讲的是巴菲特的合伙人查理芒格的，于是一发不可收拾，读了巨多投资相关的书，现在已经慢慢对投资有感觉了，关于投资还是投机，
我个人选择是价值投资的基础上投机，另外也发现我这种不慌不忙、耐心的心态在投资上好像还挺好的，投资这件事我认为越早了解越好，就能越早抓住机会，我常常后悔
之前我去干嘛了？

** 17 年的工作总结
我在工作中努力避免的一点就是 1 年工作经验然后重复 5 年，17 年初我回到知道创宇，可惜做的事情还是我很熟悉的，在帮助团队搭建完基础技术架构后，我便开始重复
工作经验，说实话这样的工作确实挺无聊的，18 年初我开始做项目管理的工作，而我个人的想法也是把自己会的技能带给团队，让其他人避免走弯路，而我也意识到自己还
可以创造更大的价值，也许在创宇待的时间不会太长了，希望之后能遇到自己的导师。

** 关于爱情
17 年中旬，遇到了一个很可爱的女孩，坚强，善良，率真，会做很多菜，喜欢哆啦A梦，有一双肉肉的小手，只是有点不自信，而我自己也许太久没有恋爱，陷在之前的感情
太久，常常很矛盾，我尽可能的好好对待她和这份感情，也试图了解自己对于爱情究竟想要什么，因此我只把这个消息告诉了家人，并没有告诉身边的同事。

** 2018 我想对自己说

1. 更专注，完成 MentorHub 和 Twister。
2. 开始投资，开始狩猎。
3. 好好对待家人，好好对待感情。
4. 可以找一份让自己更有热情的工作。
